// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/workflow-goclient/models"
)

// ActivityHeartbeatReader is a Reader for the ActivityHeartbeat structure.
type ActivityHeartbeatReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ActivityHeartbeatReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewActivityHeartbeatOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewActivityHeartbeatUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewActivityHeartbeatForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewActivityHeartbeatNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewActivityHeartbeatDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewActivityHeartbeatOK creates a ActivityHeartbeatOK with default headers values
func NewActivityHeartbeatOK() *ActivityHeartbeatOK {
	return &ActivityHeartbeatOK{}
}

/*ActivityHeartbeatOK handles this case with default header values.

activity heart beat acknowledged. Cancelled field in return value should be checked to determine if activity has been cancelled.
*/
type ActivityHeartbeatOK struct {
	Payload *models.Heartbeat
}

func (o *ActivityHeartbeatOK) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] activityHeartbeatOK  %+v", 200, o.Payload)
}

func (o *ActivityHeartbeatOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Heartbeat)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivityHeartbeatUnauthorized creates a ActivityHeartbeatUnauthorized with default headers values
func NewActivityHeartbeatUnauthorized() *ActivityHeartbeatUnauthorized {
	return &ActivityHeartbeatUnauthorized{}
}

/*ActivityHeartbeatUnauthorized handles this case with default header values.

Not authorized
*/
type ActivityHeartbeatUnauthorized struct {
	Payload *models.Error
}

func (o *ActivityHeartbeatUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] activityHeartbeatUnauthorized  %+v", 401, o.Payload)
}

func (o *ActivityHeartbeatUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivityHeartbeatForbidden creates a ActivityHeartbeatForbidden with default headers values
func NewActivityHeartbeatForbidden() *ActivityHeartbeatForbidden {
	return &ActivityHeartbeatForbidden{}
}

/*ActivityHeartbeatForbidden handles this case with default header values.

Forbidden
*/
type ActivityHeartbeatForbidden struct {
	Payload *models.Error
}

func (o *ActivityHeartbeatForbidden) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] activityHeartbeatForbidden  %+v", 403, o.Payload)
}

func (o *ActivityHeartbeatForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewActivityHeartbeatNotFound creates a ActivityHeartbeatNotFound with default headers values
func NewActivityHeartbeatNotFound() *ActivityHeartbeatNotFound {
	return &ActivityHeartbeatNotFound{}
}

/*ActivityHeartbeatNotFound handles this case with default header values.

Not found
*/
type ActivityHeartbeatNotFound struct {
}

func (o *ActivityHeartbeatNotFound) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] activityHeartbeatNotFound ", 404)
}

func (o *ActivityHeartbeatNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewActivityHeartbeatDefault creates a ActivityHeartbeatDefault with default headers values
func NewActivityHeartbeatDefault(code int) *ActivityHeartbeatDefault {
	return &ActivityHeartbeatDefault{
		_statusCode: code,
	}
}

/*ActivityHeartbeatDefault handles this case with default header values.

unexpected error
*/
type ActivityHeartbeatDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the activity heartbeat default response
func (o *ActivityHeartbeatDefault) Code() int {
	return o._statusCode
}

func (o *ActivityHeartbeatDefault) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] activityHeartbeat default  %+v", o._statusCode, o.Payload)
}

func (o *ActivityHeartbeatDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
