// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCancelWorkflowParams creates a new CancelWorkflowParams object
// with the default values initialized.
func NewCancelWorkflowParams() *CancelWorkflowParams {
	var ()
	return &CancelWorkflowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCancelWorkflowParamsWithTimeout creates a new CancelWorkflowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCancelWorkflowParamsWithTimeout(timeout time.Duration) *CancelWorkflowParams {
	var ()
	return &CancelWorkflowParams{

		timeout: timeout,
	}
}

// NewCancelWorkflowParamsWithContext creates a new CancelWorkflowParams object
// with the default values initialized, and the ability to set a context for a request
func NewCancelWorkflowParamsWithContext(ctx context.Context) *CancelWorkflowParams {
	var ()
	return &CancelWorkflowParams{

		Context: ctx,
	}
}

// NewCancelWorkflowParamsWithHTTPClient creates a new CancelWorkflowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCancelWorkflowParamsWithHTTPClient(client *http.Client) *CancelWorkflowParams {
	var ()
	return &CancelWorkflowParams{
		HTTPClient: client,
	}
}

/*CancelWorkflowParams contains all the parameters to send to the API endpoint
for the cancel workflow operation typically these are written to a http.Request
*/
type CancelWorkflowParams struct {

	/*ID
	  ID of workflow

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the cancel workflow params
func (o *CancelWorkflowParams) WithTimeout(timeout time.Duration) *CancelWorkflowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the cancel workflow params
func (o *CancelWorkflowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the cancel workflow params
func (o *CancelWorkflowParams) WithContext(ctx context.Context) *CancelWorkflowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the cancel workflow params
func (o *CancelWorkflowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the cancel workflow params
func (o *CancelWorkflowParams) WithHTTPClient(client *http.Client) *CancelWorkflowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the cancel workflow params
func (o *CancelWorkflowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the cancel workflow params
func (o *CancelWorkflowParams) WithID(id string) *CancelWorkflowParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the cancel workflow params
func (o *CancelWorkflowParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CancelWorkflowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
