// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/workflow-goclient/models"
)

// HeartbeatActivityReader is a Reader for the HeartbeatActivity structure.
type HeartbeatActivityReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HeartbeatActivityReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewHeartbeatActivityOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewHeartbeatActivityUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewHeartbeatActivityForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewHeartbeatActivityNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewHeartbeatActivityDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewHeartbeatActivityOK creates a HeartbeatActivityOK with default headers values
func NewHeartbeatActivityOK() *HeartbeatActivityOK {
	return &HeartbeatActivityOK{}
}

/*HeartbeatActivityOK handles this case with default header values.

Activity heart beat acknowledged. Cancelled field in return value should be checked to determine if activity has been cancelled.
*/
type HeartbeatActivityOK struct {
	Payload *models.Heartbeat
}

func (o *HeartbeatActivityOK) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] heartbeatActivityOK  %+v", 200, o.Payload)
}

func (o *HeartbeatActivityOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Heartbeat)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHeartbeatActivityUnauthorized creates a HeartbeatActivityUnauthorized with default headers values
func NewHeartbeatActivityUnauthorized() *HeartbeatActivityUnauthorized {
	return &HeartbeatActivityUnauthorized{}
}

/*HeartbeatActivityUnauthorized handles this case with default header values.

Not authorized
*/
type HeartbeatActivityUnauthorized struct {
	Payload *models.Error
}

func (o *HeartbeatActivityUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] heartbeatActivityUnauthorized  %+v", 401, o.Payload)
}

func (o *HeartbeatActivityUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHeartbeatActivityForbidden creates a HeartbeatActivityForbidden with default headers values
func NewHeartbeatActivityForbidden() *HeartbeatActivityForbidden {
	return &HeartbeatActivityForbidden{}
}

/*HeartbeatActivityForbidden handles this case with default header values.

Forbidden
*/
type HeartbeatActivityForbidden struct {
	Payload *models.Error
}

func (o *HeartbeatActivityForbidden) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] heartbeatActivityForbidden  %+v", 403, o.Payload)
}

func (o *HeartbeatActivityForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewHeartbeatActivityNotFound creates a HeartbeatActivityNotFound with default headers values
func NewHeartbeatActivityNotFound() *HeartbeatActivityNotFound {
	return &HeartbeatActivityNotFound{}
}

/*HeartbeatActivityNotFound handles this case with default header values.

Not found
*/
type HeartbeatActivityNotFound struct {
}

func (o *HeartbeatActivityNotFound) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] heartbeatActivityNotFound ", 404)
}

func (o *HeartbeatActivityNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewHeartbeatActivityDefault creates a HeartbeatActivityDefault with default headers values
func NewHeartbeatActivityDefault(code int) *HeartbeatActivityDefault {
	return &HeartbeatActivityDefault{
		_statusCode: code,
	}
}

/*HeartbeatActivityDefault handles this case with default header values.

unexpected error
*/
type HeartbeatActivityDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the heartbeat activity default response
func (o *HeartbeatActivityDefault) Code() int {
	return o._statusCode
}

func (o *HeartbeatActivityDefault) Error() string {
	return fmt.Sprintf("[PUT /workflows/{id}/activities/{activityId}/heartbeat][%d] heartbeatActivity default  %+v", o._statusCode, o.Payload)
}

func (o *HeartbeatActivityDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
