// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/workflow-goclient/models"
)

// NewHeartbeatParams creates a new HeartbeatParams object
// with the default values initialized.
func NewHeartbeatParams() *HeartbeatParams {
	var ()
	return &HeartbeatParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHeartbeatParamsWithTimeout creates a new HeartbeatParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHeartbeatParamsWithTimeout(timeout time.Duration) *HeartbeatParams {
	var ()
	return &HeartbeatParams{

		timeout: timeout,
	}
}

// NewHeartbeatParamsWithContext creates a new HeartbeatParams object
// with the default values initialized, and the ability to set a context for a request
func NewHeartbeatParamsWithContext(ctx context.Context) *HeartbeatParams {
	var ()
	return &HeartbeatParams{

		Context: ctx,
	}
}

// NewHeartbeatParamsWithHTTPClient creates a new HeartbeatParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHeartbeatParamsWithHTTPClient(client *http.Client) *HeartbeatParams {
	var ()
	return &HeartbeatParams{
		HTTPClient: client,
	}
}

/*HeartbeatParams contains all the parameters to send to the API endpoint
for the heartbeat operation typically these are written to a http.Request
*/
type HeartbeatParams struct {

	/*Heartbeat*/
	Heartbeat *models.Heartbeat

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the heartbeat params
func (o *HeartbeatParams) WithTimeout(timeout time.Duration) *HeartbeatParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the heartbeat params
func (o *HeartbeatParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the heartbeat params
func (o *HeartbeatParams) WithContext(ctx context.Context) *HeartbeatParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the heartbeat params
func (o *HeartbeatParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the heartbeat params
func (o *HeartbeatParams) WithHTTPClient(client *http.Client) *HeartbeatParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the heartbeat params
func (o *HeartbeatParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHeartbeat adds the heartbeat to the heartbeat params
func (o *HeartbeatParams) WithHeartbeat(heartbeat *models.Heartbeat) *HeartbeatParams {
	o.SetHeartbeat(heartbeat)
	return o
}

// SetHeartbeat adds the heartbeat to the heartbeat params
func (o *HeartbeatParams) SetHeartbeat(heartbeat *models.Heartbeat) {
	o.Heartbeat = heartbeat
}

// WriteToRequest writes these params to a swagger request
func (o *HeartbeatParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Heartbeat == nil {
		o.Heartbeat = new(models.Heartbeat)
	}

	if err := r.SetBodyParam(o.Heartbeat); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
