// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/workflow-goclient/models"
)

// NewHeartbeatActivityParams creates a new HeartbeatActivityParams object
// with the default values initialized.
func NewHeartbeatActivityParams() *HeartbeatActivityParams {
	var ()
	return &HeartbeatActivityParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewHeartbeatActivityParamsWithTimeout creates a new HeartbeatActivityParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewHeartbeatActivityParamsWithTimeout(timeout time.Duration) *HeartbeatActivityParams {
	var ()
	return &HeartbeatActivityParams{

		timeout: timeout,
	}
}

// NewHeartbeatActivityParamsWithContext creates a new HeartbeatActivityParams object
// with the default values initialized, and the ability to set a context for a request
func NewHeartbeatActivityParamsWithContext(ctx context.Context) *HeartbeatActivityParams {
	var ()
	return &HeartbeatActivityParams{

		Context: ctx,
	}
}

// NewHeartbeatActivityParamsWithHTTPClient creates a new HeartbeatActivityParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewHeartbeatActivityParamsWithHTTPClient(client *http.Client) *HeartbeatActivityParams {
	var ()
	return &HeartbeatActivityParams{
		HTTPClient: client,
	}
}

/*HeartbeatActivityParams contains all the parameters to send to the API endpoint
for the heartbeat activity operation typically these are written to a http.Request
*/
type HeartbeatActivityParams struct {

	/*ActivityID
	  ID of activity

	*/
	ActivityID string
	/*Heartbeat*/
	Heartbeat *models.Heartbeat
	/*ID
	  ID of workflow

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the heartbeat activity params
func (o *HeartbeatActivityParams) WithTimeout(timeout time.Duration) *HeartbeatActivityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the heartbeat activity params
func (o *HeartbeatActivityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the heartbeat activity params
func (o *HeartbeatActivityParams) WithContext(ctx context.Context) *HeartbeatActivityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the heartbeat activity params
func (o *HeartbeatActivityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the heartbeat activity params
func (o *HeartbeatActivityParams) WithHTTPClient(client *http.Client) *HeartbeatActivityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the heartbeat activity params
func (o *HeartbeatActivityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithActivityID adds the activityID to the heartbeat activity params
func (o *HeartbeatActivityParams) WithActivityID(activityID string) *HeartbeatActivityParams {
	o.SetActivityID(activityID)
	return o
}

// SetActivityID adds the activityId to the heartbeat activity params
func (o *HeartbeatActivityParams) SetActivityID(activityID string) {
	o.ActivityID = activityID
}

// WithHeartbeat adds the heartbeat to the heartbeat activity params
func (o *HeartbeatActivityParams) WithHeartbeat(heartbeat *models.Heartbeat) *HeartbeatActivityParams {
	o.SetHeartbeat(heartbeat)
	return o
}

// SetHeartbeat adds the heartbeat to the heartbeat activity params
func (o *HeartbeatActivityParams) SetHeartbeat(heartbeat *models.Heartbeat) {
	o.Heartbeat = heartbeat
}

// WithID adds the id to the heartbeat activity params
func (o *HeartbeatActivityParams) WithID(id string) *HeartbeatActivityParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the heartbeat activity params
func (o *HeartbeatActivityParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *HeartbeatActivityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param activityId
	if err := r.SetPathParam("activityId", o.ActivityID); err != nil {
		return err
	}

	if o.Heartbeat == nil {
		o.Heartbeat = new(models.Heartbeat)
	}

	if err := r.SetBodyParam(o.Heartbeat); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
