// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/3dsim/workflow-goclient/models"
)

// NewStartWorkflowParams creates a new StartWorkflowParams object
// with the default values initialized.
func NewStartWorkflowParams() *StartWorkflowParams {
	var ()
	return &StartWorkflowParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStartWorkflowParamsWithTimeout creates a new StartWorkflowParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStartWorkflowParamsWithTimeout(timeout time.Duration) *StartWorkflowParams {
	var ()
	return &StartWorkflowParams{

		timeout: timeout,
	}
}

// NewStartWorkflowParamsWithContext creates a new StartWorkflowParams object
// with the default values initialized, and the ability to set a context for a request
func NewStartWorkflowParamsWithContext(ctx context.Context) *StartWorkflowParams {
	var ()
	return &StartWorkflowParams{

		Context: ctx,
	}
}

// NewStartWorkflowParamsWithHTTPClient creates a new StartWorkflowParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewStartWorkflowParamsWithHTTPClient(client *http.Client) *StartWorkflowParams {
	var ()
	return &StartWorkflowParams{
		HTTPClient: client,
	}
}

/*StartWorkflowParams contains all the parameters to send to the API endpoint
for the start workflow operation typically these are written to a http.Request
*/
type StartWorkflowParams struct {

	/*Workflow*/
	Workflow *models.PostWorkflow

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the start workflow params
func (o *StartWorkflowParams) WithTimeout(timeout time.Duration) *StartWorkflowParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the start workflow params
func (o *StartWorkflowParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the start workflow params
func (o *StartWorkflowParams) WithContext(ctx context.Context) *StartWorkflowParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the start workflow params
func (o *StartWorkflowParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the start workflow params
func (o *StartWorkflowParams) WithHTTPClient(client *http.Client) *StartWorkflowParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the start workflow params
func (o *StartWorkflowParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithWorkflow adds the workflow to the start workflow params
func (o *StartWorkflowParams) WithWorkflow(workflow *models.PostWorkflow) *StartWorkflowParams {
	o.SetWorkflow(workflow)
	return o
}

// SetWorkflow adds the workflow to the start workflow params
func (o *StartWorkflowParams) SetWorkflow(workflow *models.PostWorkflow) {
	o.Workflow = workflow
}

// WriteToRequest writes these params to a swagger request
func (o *StartWorkflowParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Workflow == nil {
		o.Workflow = new(models.PostWorkflow)
	}

	if err := r.SetBodyParam(o.Workflow); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
