// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Heartbeat heartbeat
// swagger:model heartbeat
type Heartbeat struct {

	// activity ID
	// Required: true
	ActivityID *string `json:"activityId"`

	// Only valid in return message. True if activity has been cancelled, false otherwise.
	Cancelled bool `json:"cancelled,omitempty"`

	// details
	Details string `json:"details,omitempty"`

	// task token
	// Required: true
	TaskToken *string `json:"taskToken"`
}

// Validate validates this heartbeat
func (m *Heartbeat) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateActivityID(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTaskToken(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Heartbeat) validateActivityID(formats strfmt.Registry) error {

	if err := validate.Required("activityId", "body", m.ActivityID); err != nil {
		return err
	}

	return nil
}

func (m *Heartbeat) validateTaskToken(formats strfmt.Registry) error {

	if err := validate.Required("taskToken", "body", m.TaskToken); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Heartbeat) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Heartbeat) UnmarshalBinary(b []byte) error {
	var res Heartbeat
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
