// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UserOutputFile Metadata container for user output files
// swagger:model userOutputFile
type UserOutputFile struct {

	// Short description of file which will appear in UI
	// Required: true
	Description *string `json:"description"`

	// File path relative to S3 bucket
	// Required: true
	S3Key *string `json:"s3Key"`
}

// Validate validates this user output file
func (m *UserOutputFile) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDescription(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateS3Key(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UserOutputFile) validateDescription(formats strfmt.Registry) error {

	if err := validate.Required("description", "body", m.Description); err != nil {
		return err
	}

	return nil
}

func (m *UserOutputFile) validateS3Key(formats strfmt.Registry) error {

	if err := validate.Required("s3Key", "body", m.S3Key); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *UserOutputFile) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UserOutputFile) UnmarshalBinary(b []byte) error {
	var res UserOutputFile
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
